/// `brief doc` — generate Markdown documentation from a `.brief` source file.
///
/// Produces a human-readable reference page showing:
/// - Tasks: goal, uses, steps, and perform calls
/// - Sealed types and structs
/// - Inline effects with function signatures
/// - Type aliases and effect group aliases
/// - Import list
///
/// Output is written to stdout (or a file if `--output` is given).

use std::fmt::Write as FmtWrite;
use std::path::Path;

use crate::ast::*;
use crate::errors::print_diagnostics;
use crate::lexer::lex;
use crate::parser::parse;

// ─────────────────────────────────────────────────────────────────────────────

/// Generate Markdown documentation for the given `.brief` file.
/// Returns `true` on success, `false` if parse errors prevented generation.
pub fn doc_file(path: &Path, output: Option<&Path>) -> bool {
    let source = match std::fs::read_to_string(path) {
        Ok(s)  => s,
        Err(e) => { eprintln!("error: cannot read {}: {e}", path.display()); return false; }
    };

    let (tokens, lex_errs) = lex(&source);
    let (program, parse_errs) = parse(&tokens, &source);

    if !lex_errs.is_empty() || !parse_errs.is_empty() {
        print_diagnostics(&parse_errs, &source, &path.display().to_string());
        if !lex_errs.is_empty() {
            for (start, end) in &lex_errs {
                eprintln!("lex error at bytes {start}–{end}");
            }
        }
        return false;
    }

    let stem = path.file_stem().unwrap_or_default().to_string_lossy();
    let md   = render(&program, &stem);

    match output {
        Some(out) => {
            if let Err(e) = std::fs::write(out, &md) {
                eprintln!("error: cannot write {}: {e}", out.display());
                return false;
            }
            println!("📄 Wrote {}", out.display());
        }
        None => print!("{md}"),
    }
    true
}

// ─────────────────────────────────────────────────────────────────────────────

fn render(program: &Program, title: &str) -> String {
    let mut out = String::new();

    // Title
    writeln!(out, "# `{title}.brief`").ok();
    writeln!(out).ok();
    writeln!(out, "> Generated by `brief doc`. Edit the source file to update.").ok();
    writeln!(out).ok();

    // Table of contents
    if !program.tasks.is_empty() || !program.types.is_empty() || !program.effects.is_empty() {
        writeln!(out, "## Contents").ok();
        writeln!(out).ok();
        if !program.imports.is_empty() {
            writeln!(out, "- [Skills](#skills)").ok();
        }
        if !program.type_aliases.is_empty() {
            writeln!(out, "- [Type Aliases](#type-aliases)").ok();
        }
        if !program.effect_groups.is_empty() {
            writeln!(out, "- [Effect Groups](#effect-groups)").ok();
        }
        if !program.types.is_empty() {
            writeln!(out, "- [Sealed Types](#sealed-types)").ok();
        }
        if !program.structs.is_empty() {
            writeln!(out, "- [Structs](#structs)").ok();
        }
        if !program.effects.is_empty() {
            writeln!(out, "- [Effects](#effects)").ok();
        }
        for task in &program.tasks {
            let slug = task.name.to_lowercase();
            writeln!(out, "- [Task: {}](#{slug})", task.name).ok();
        }
        writeln!(out).ok();
    }

    // ── Skills ────────────────────────────────────────────────────────────────
    if !program.imports.is_empty() {
        writeln!(out, "## Skills").ok();
        writeln!(out).ok();
        for import in &program.imports {
            writeln!(out, "- `{}`", import.name).ok();
        }
        writeln!(out).ok();
    }

    // ── Type aliases ─────────────────────────────────────────────────────────
    if !program.type_aliases.is_empty() {
        writeln!(out, "## Type Aliases").ok();
        writeln!(out).ok();
        writeln!(out, "| Alias | Base | Attributes |").ok();
        writeln!(out, "|-------|------|------------|").ok();
        for alias in &program.type_aliases {
            let attrs = if alias.attrs.is_empty() {
                "—".to_string()
            } else {
                alias.attrs.iter()
                    .map(|a| if let Some(arg) = &a.arg { format!("`@{}({arg})`", a.name) } else { format!("`@{}`", a.name) })
                    .collect::<Vec<_>>()
                    .join(" ")
            };
            writeln!(out, "| `{}` | `{}` | {} |", alias.name, alias.base.name, attrs).ok();
        }
        writeln!(out).ok();
    }

    // ── Effect groups ─────────────────────────────────────────────────────────
    if !program.effect_groups.is_empty() {
        writeln!(out, "## Effect Groups").ok();
        writeln!(out).ok();
        for group in &program.effect_groups {
            let members = group.members.iter().map(|m| format!("`{m}`")).collect::<Vec<_>>().join(", ");
            writeln!(out, "- **`{}`** = [ {members} ]", group.name).ok();
        }
        writeln!(out).ok();
    }

    // ── Sealed types ─────────────────────────────────────────────────────────
    if !program.types.is_empty() {
        writeln!(out, "## Sealed Types").ok();
        writeln!(out).ok();
        for ty in &program.types {
            let params = if ty.params.is_empty() { String::new() } else { format!("<{}>", ty.params.join(", ")) };
            writeln!(out, "### `{}{}`", ty.name, params).ok();
            writeln!(out).ok();
            writeln!(out, "| Variant | Fields |").ok();
            writeln!(out, "|---------|--------|").ok();
            for v in &ty.variants {
                let fields = if v.fields.is_empty() {
                    "—".to_string()
                } else {
                    v.fields.iter().map(|f| format!("`{}`", type_ref_str(f))).collect::<Vec<_>>().join(", ")
                };
                writeln!(out, "| `{}` | {} |", v.name, fields).ok();
            }
            writeln!(out).ok();
        }
    }

    // ── Structs ───────────────────────────────────────────────────────────────
    if !program.structs.is_empty() {
        writeln!(out, "## Structs").ok();
        writeln!(out).ok();
        for s in &program.structs {
            let params = if s.params.is_empty() { String::new() } else { format!("<{}>", s.params.join(", ")) };
            writeln!(out, "### `{}{}`", s.name, params).ok();
            writeln!(out).ok();
            writeln!(out, "| Field | Type | Constraints |").ok();
            writeln!(out, "|-------|------|-------------|").ok();
            for f in &s.fields {
                let constraints = if f.attrs.is_empty() {
                    "—".to_string()
                } else {
                    f.attrs.iter()
                        .map(|a| if let Some(arg) = &a.arg { format!("`@{}({arg})`", a.name) } else { format!("`@{}`", a.name) })
                        .collect::<Vec<_>>()
                        .join(" ")
                };
                writeln!(out, "| `{}` | `{}` | {} |", f.name, type_ref_str(&f.ty), constraints).ok();
            }
            writeln!(out).ok();
        }
    }

    // ── Inline effects ────────────────────────────────────────────────────────
    if !program.effects.is_empty() {
        writeln!(out, "## Effects").ok();
        writeln!(out).ok();
        for effect in &program.effects {
            writeln!(out, "### `{}`", effect.name).ok();
            writeln!(out).ok();
            writeln!(out, "| Function | Parameters | Returns |").ok();
            writeln!(out, "|----------|------------|---------|").ok();
            for f in &effect.fns {
                let params = if f.params.is_empty() {
                    "—".to_string()
                } else {
                    f.params.iter()
                        .map(|p| {
                            let attrs = p.attrs.iter().map(|a| format!("@{}", a.name)).collect::<Vec<_>>().join(" ");
                            if attrs.is_empty() {
                                format!("`{}: {}`", p.name, type_ref_str(&p.ty))
                            } else {
                                format!("`{}: {attrs} {}`", p.name, type_ref_str(&p.ty))
                            }
                        })
                        .collect::<Vec<_>>()
                        .join(", ")
                };
                let ret_attrs = f.ret_attrs.iter()
                    .map(|a| format!("@{}", a.name))
                    .collect::<Vec<_>>()
                    .join(" ");
                let ret_str = if ret_attrs.is_empty() {
                    format!("`{}`", type_ref_str(&f.ret))
                } else {
                    format!("`{ret_attrs} {}`", type_ref_str(&f.ret))
                };
                writeln!(out, "| `{}` | {} | {} |", f.name, params, ret_str).ok();
            }
            writeln!(out).ok();
        }
    }

    // ── Tasks ─────────────────────────────────────────────────────────────────
    for task in &program.tasks {
        render_task(task, &mut out);
    }

    out
}

fn render_task(task: &Task, out: &mut String) {
    // Heading
    let slug = task.name.to_lowercase();
    writeln!(out, "## Task: `{}` {{#{slug}}}", task.name).ok();
    writeln!(out).ok();

    // Decorators
    if !task.decorators.is_empty() {
        let decs = task.decorators.iter()
            .map(|d| if let Some(arg) = &d.arg { format!("`@{}({arg})`", d.name) } else { format!("`@{}`", d.name) })
            .collect::<Vec<_>>()
            .join(" ");
        writeln!(out, "**Decorators:** {decs}  ").ok();
    }

    // Goal
    if let Some(goal) = &task.goal {
        writeln!(out, "**Goal:** {goal}  ").ok();
    }

    // Uses
    if !task.uses.is_empty() {
        let uses = task.uses.iter().map(|u| format!("`{u}`")).collect::<Vec<_>>().join(", ");
        writeln!(out, "**Uses:** {uses}  ").ok();
    }

    // Extras
    if !task.extras.is_empty() {
        writeln!(out).ok();
        writeln!(out, "**Metadata:**").ok();
        writeln!(out).ok();
        writeln!(out, "| Key | Value |").ok();
        writeln!(out, "|-----|-------|").ok();
        for (k, v) in &task.extras {
            writeln!(out, "| `{k}` | `{v}` |").ok();
        }
    }

    writeln!(out).ok();

    // Steps
    if !task.steps.is_empty() {
        writeln!(out, "### Steps").ok();
        writeln!(out).ok();
        for step in &task.steps {
            writeln!(out, "#### `{}`", step.name).ok();
            writeln!(out).ok();
            if step.body.is_empty() {
                writeln!(out, "_empty step_").ok();
            } else {
                writeln!(out, "```brief").ok();
                for stmt in &step.body {
                    render_stmt(stmt, out);
                }
                writeln!(out, "```").ok();
            }
            writeln!(out).ok();

            // Perform call summary
            let performs: Vec<_> = step.body.iter()
                .filter_map(|s| match s {
                    Stmt::Let  { value: Expr::Perform { skill, func, .. }, name, .. } => Some((name.as_str(), skill.as_str(), func.as_str())),
                    Stmt::Expr { value: Expr::Perform { skill, func, .. }, .. }       => Some(("_", skill.as_str(), func.as_str())),
                    _ => None,
                })
                .collect();

            if !performs.is_empty() {
                writeln!(out, "| Binding | Skill | Function |").ok();
                writeln!(out, "|---------|-------|----------|").ok();
                for (binding, skill, func) in &performs {
                    writeln!(out, "| `{binding}` | `{skill}` | `{func}` |").ok();
                }
                writeln!(out).ok();
            }
        }
    }
}

fn render_stmt(stmt: &Stmt, out: &mut String) {
    match stmt {
        Stmt::Let { attrs, name, value, .. } => {
            let prefix = if attrs.iter().any(|a| a == "once" || a == "affine") {
                format!("@{} ", attrs[0])
            } else {
                String::new()
            };
            writeln!(out, "    {prefix}let {name} = {};", expr_str(value)).ok();
        }
        Stmt::Expr { value, .. } => {
            writeln!(out, "    {};", expr_str(value)).ok();
        }
    }
}

fn expr_str(expr: &Expr) -> String {
    match expr {
        Expr::Perform { skill, func, args, propagate, .. } => {
            let arg_str = args.iter().map(expr_str).collect::<Vec<_>>().join(", ");
            let q = if *propagate { "?" } else { "" };
            format!("perform {skill}.{func}({arg_str}){q}")
        }
        Expr::Await { expr, .. } => format!("await {}", expr_str(expr)),
        Expr::Call { receiver, func, args, .. } => {
            let arg_str = args.iter().map(expr_str).collect::<Vec<_>>().join(", ");
            match receiver {
                Some(r) => format!("{r}.{func}({arg_str})"),
                None    => format!("{func}({arg_str})"),
            }
        }
        Expr::Ident { name, .. } => name.clone(),
        Expr::Str   { value, .. } => format!("\"{value}\""),
        Expr::Int   { value, .. } => value.to_string(),
    }
}

fn type_ref_str(ty: &TypeRef) -> String {
    let mut s = ty.name.clone();
    if !ty.args.is_empty() {
        let args = ty.args.iter().map(type_ref_str).collect::<Vec<_>>().join(", ");
        s.push_str(&format!("<{args}>"));
    }
    if ty.optional { s.push('?'); }
    s
}

// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::lexer::lex;
    use crate::parser::parse;

    fn doc_src(src: &str) -> String {
        let (tokens, _) = lex(src);
        let (program, _) = parse(&tokens, src);
        render(&program, "test")
    }

    #[test]
    fn renders_task_goal() {
        let md = doc_src(r#"task Hello : TaskBrief { goal = "Say hello" }"#);
        assert!(md.contains("Say hello"), "missing goal in:\n{md}");
    }

    #[test]
    fn renders_type_alias_table() {
        let md = doc_src(r#"type Email = @matches("[^@]+") String"#);
        assert!(md.contains("## Type Aliases"), "missing section:\n{md}");
        assert!(md.contains("Email"), "{md}");
        assert!(md.contains("@matches"), "{md}");
    }

    #[test]
    fn renders_effect_group() {
        let md = doc_src(r#"type AuthEffects = [Auth, Session]"#);
        assert!(md.contains("## Effect Groups"), "{md}");
        assert!(md.contains("AuthEffects"), "{md}");
        assert!(md.contains("Auth"), "{md}");
    }

    #[test]
    fn renders_sealed_type_variants() {
        let md = doc_src(r#"sealed type Status = Active | Inactive | Suspended(String)"#);
        assert!(md.contains("## Sealed Types"), "{md}");
        assert!(md.contains("Active"), "{md}");
        assert!(md.contains("Suspended"), "{md}");
    }

    #[test]
    fn renders_inline_effect_with_once() {
        let md = doc_src(r#"
            effect Payment {
                fn charge(amount: String) -> @once Handle
            }
        "#);
        assert!(md.contains("## Effects"), "{md}");
        assert!(md.contains("@once"), "{md}");
        assert!(md.contains("charge"), "{md}");
    }

    #[test]
    fn renders_perform_calls_in_step() {
        let md = doc_src(r#"
            import skill "GraphQL"
            task Fetch : TaskBrief uses [GraphQL] {
                goal = "fetch user"
                step Load {
                    let user = perform GraphQL.query(userQuery)?;
                }
            }
        "#);
        assert!(md.contains("GraphQL"), "{md}");
        assert!(md.contains("query"), "{md}");
        assert!(md.contains("user"), "{md}");
    }

    #[test]
    fn renders_toc_with_tasks() {
        let md = doc_src(r#"task Foo : TaskBrief { goal = "x" }"#);
        assert!(md.contains("## Contents"), "{md}");
        assert!(md.contains("Task: Foo"), "{md}");
    }

    #[test]
    fn renders_struct_with_constraints() {
        let md = doc_src(r#"
            struct User {
                email: @matches("[^@]+") String
                name: @nonEmpty String
            }
        "#);
        assert!(md.contains("## Structs"), "{md}");
        assert!(md.contains("email"), "{md}");
        assert!(md.contains("@matches"), "{md}");
        assert!(md.contains("@nonEmpty"), "{md}");
    }
}
