/// `brief gen` — generates a `.brief` file from a natural language description.
///
/// v0.0.1: Produces a structured template with the description embedded.
/// v0.1 (planned): Calls a configured LLM (OpenAI / Anthropic / Ollama) via BRIEF_LLM_API_KEY.

use std::path::Path;
use colored::Colorize;

pub fn gen(description: &str, output: Option<&Path>) {
    println!("{} Generating brief from description...", "●".blue().bold());
    println!("  {}", description.italic());
    println!();

    // Derive a PascalCase task name from the description.
    let task_name = description_to_task_name(description);

    // v0.0.1: emit a structured template with the description as the goal.
    let brief = render_brief_template(&task_name, description);

    let output_path = output
        .map(|p| p.to_string_lossy().to_string())
        .unwrap_or_else(|| format!("{task_name}.brief"));

    match std::fs::write(&output_path, &brief) {
        Ok(_) => {
            println!("{} Generated: {}", "✅".green().bold(), output_path.green().bold());
            println!();
            println!("{}", "Review and run `brief check` to validate:".dimmed());
            println!("{}", brief);
            println!();
            println!("{}", "Next steps:".bold());
            println!("  1. Add `import skill` declarations for any skills you need");
            println!("  2. Add steps to describe the workflow");
            println!("  3. Run {} to validate", "`brief check`".cyan());
            println!();
            println!("{} LLM-powered generation coming in v0.1 (set BRIEF_LLM_API_KEY)", "💡".yellow());
        }
        Err(e) => {
            eprintln!("{}: cannot write {}: {}", "error".red().bold(), output_path, e);
            std::process::exit(1);
        }
    }
}

fn description_to_task_name(desc: &str) -> String {
    desc.split_whitespace()
        .take(4)
        .map(|word| {
            let clean: String = word.chars().filter(|c| c.is_alphanumeric()).collect();
            let mut chars = clean.chars();
            match chars.next() {
                None    => String::new(),
                Some(c) => c.to_uppercase().to_string() + chars.as_str(),
            }
        })
        .collect::<String>()
}

fn render_brief_template(task_name: &str, description: &str) -> String {
    format!(
        r#"// Generated by `brief gen`
// Review and customise before use.

@BriefBuilder
task {task_name} : TaskBrief {{
    goal = "{description}"

    // TODO: add `import skill "SkillName"` for each skill you need
    // TODO: add steps to define the workflow

    // Example:
    // step FetchData {{
    //     let result = perform MySkill.operation(input)?;
    // }}
}}
"#
    )
}
