/// `brief skillsync` — auto-generate `.briefskill` interface files from live MCP servers.
///
/// For each skill configured in `brief.toml`, connects to its MCP server,
/// calls `tools/list`, and generates a `.briefskill` file matching the real interface.
///
/// Usage:
///   brief skillsync [--yes]   # --yes skips confirmation when file already exists
use colored::Colorize;
use std::path::{Path, PathBuf};

use crate::manifest;
use crate::verifier::{self, ToolMeta};

pub fn run_skillsync(cwd: &Path, yes: bool) -> bool {
    // ── 1. Load manifest ─────────────────────────────────────────────────────
    let mf = match manifest::load_manifest(cwd) {
        Some(m) => m,
        None => {
            eprintln!("{}: no brief.toml found in {} or any parent directory",
                "error".red().bold(), cwd.display());
            return false;
        }
    };

    if mf.skills.is_empty() {
        eprintln!("{} No skills configured in brief.toml.", "warn".yellow().bold());
        eprintln!("  Add a [skills.SkillName] section with mcp_command or mcp_url.");
        return true;
    }

    let mut all_ok = true;
    let skills: Vec<(String, _)> = mf.skills.iter()
        .map(|(k, v)| (k.clone(), v.as_config()))
        .collect();

    for (skill_name, config) in &skills {
        eprintln!("{} Syncing {} ...", "→".cyan(), skill_name.bold());

        // ── 2. Connect and list tools ────────────────────────────────────────
        let tools = match verifier::list_skill_tools_meta(config, skill_name) {
            Ok(t) => t,
            Err(e) => {
                eprintln!("  {} {}: {e}", "error".red().bold(), skill_name);
                all_ok = false;
                continue;
            }
        };

        eprintln!("  {} {} function(s) discovered", "✓".green(), tools.len());

        // ── 3. Generate .briefskill content ─────────────────────────────────
        let new_content = render_skillsync(skill_name, &tools);

        // ── 4. Determine output path ─────────────────────────────────────────
        let out_path = if let Some(p) = &config.path {
            // Use configured path as directory, write <SkillName>.briefskill inside it.
            let dir = Path::new(p);
            dir.join(format!("{skill_name}.briefskill"))
        } else {
            // Default: .claude/skills/<SkillName>/<SkillName>.briefskill
            cwd.join(".claude")
               .join("skills")
               .join(skill_name)
               .join(format!("{skill_name}.briefskill"))
        };

        // ── 5. Write or update file ──────────────────────────────────────────
        if out_path.exists() {
            let existing = std::fs::read_to_string(&out_path).unwrap_or_default();
            if existing == new_content {
                eprintln!("  {} {} is up-to-date", "✓".green(), out_path.display());
                continue;
            }
            // Show diff.
            eprintln!("  {} {} differs from current server interface",
                "!".yellow(), out_path.display());
            print_diff(&existing, &new_content);
            if !yes {
                eprint!("  Overwrite? [y/N] ");
                let mut line = String::new();
                let _ = std::io::stdin().read_line(&mut line);
                if !line.trim().eq_ignore_ascii_case("y") {
                    eprintln!("  {} Skipped {skill_name}", "↷".dimmed());
                    continue;
                }
            }
        }

        if let Some(parent) = out_path.parent() {
            let _ = std::fs::create_dir_all(parent);
        }
        match std::fs::write(&out_path, &new_content) {
            Ok(()) => eprintln!("  {} Written {}", "✓".green(), out_path.display()),
            Err(e) => {
                eprintln!("  {} Cannot write {}: {e}", "error".red().bold(), out_path.display());
                all_ok = false;
            }
        }
    }

    all_ok
}

/// Render a `.briefskill` file from live `ToolMeta` data.
fn render_skillsync(skill_name: &str, tools: &[ToolMeta]) -> String {
    let mut out = String::new();
    out.push_str(&format!(
        "// Auto-generated by `brief skillsync v{}`\n\
         // Regenerate: brief skillsync\n\
         // Do not edit manually — run `brief skillsync` to refresh.\n\n",
        env!("CARGO_PKG_VERSION")
    ));

    out.push_str(&format!("interface {skill_name} {{\n"));

    for tool in tools {
        // Function name: strip "SkillName." prefix if present.
        let bare_name = if let Some((_, f)) = tool.name.split_once('.') { f } else { &tool.name };

        // Optional doc comment from description.
        if let Some(desc) = &tool.description {
            let trimmed = desc.trim();
            if !trimmed.is_empty() {
                out.push_str(&format!("    /// {trimmed}\n"));
            }
        }

        // Parse input schema to get typed parameters.
        let params = extract_params(&tool.input_schema);
        let params_str = params.join(", ");

        out.push_str(&format!("    fn {bare_name}({params_str}) -> String\n"));
    }

    out.push_str("}\n");
    out
}

/// Extract typed parameters from a JSON Schema `inputSchema` object.
fn extract_params(schema: &Option<serde_json::Value>) -> Vec<String> {
    let schema = match schema {
        Some(s) => s,
        None => return vec![],
    };

    let props = match schema.get("properties").and_then(|p| p.as_object()) {
        Some(p) => p,
        None => return vec![],
    };

    let required: std::collections::HashSet<&str> = schema
        .get("required")
        .and_then(|r| r.as_array())
        .map(|arr| arr.iter().filter_map(|v| v.as_str()).collect())
        .unwrap_or_default();

    let mut params = Vec::new();
    for (name, prop) in props {
        let brief_type = json_schema_to_brief_type(prop);
        if required.contains(name.as_str()) {
            params.push(format!("{name}: {brief_type}"));
        } else {
            params.push(format!("{name}: {brief_type}?"));
        }
    }
    params
}

/// Map a JSON Schema type to a Brief type.
fn json_schema_to_brief_type(prop: &serde_json::Value) -> &'static str {
    match prop.get("type").and_then(|t| t.as_str()) {
        Some("integer") | Some("number") => "Int",
        Some("boolean") => "Bool",
        Some("string") => "String",
        Some("array") | Some("object") => "String", // fallback for complex types
        // oneOf/anyOf/allOf → fallback
        _ => "String",
    }
}

/// Print a simple text diff (added/removed lines) between old and new content.
fn print_diff(old: &str, new: &str) {
    use std::collections::HashSet;
    let old_lines: HashSet<&str> = old.lines().collect();
    let new_lines: HashSet<&str> = new.lines().collect();

    for line in old.lines() {
        if !new_lines.contains(line) {
            eprintln!("    {} {}", "-".red(), line);
        }
    }
    for line in new.lines() {
        if !old_lines.contains(line) {
            eprintln!("    {} {}", "+".green(), line);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::verifier::ToolMeta;
    use serde_json::json;

    fn tool(name: &str, desc: Option<&str>, schema: Option<serde_json::Value>) -> ToolMeta {
        ToolMeta {
            name: name.to_string(),
            description: desc.map(str::to_string),
            input_schema: schema,
        }
    }

    #[test]
    fn renders_empty_interface() {
        let content = render_skillsync("GitHub", &[]);
        assert!(content.contains("interface GitHub {"));
        assert!(content.contains("brief skillsync"));
    }

    #[test]
    fn renders_functions_with_types() {
        let tools = vec![
            tool(
                "GitHub.get_pull_request",
                Some("Get a pull request"),
                Some(json!({
                    "type": "object",
                    "properties": {
                        "owner": { "type": "string" },
                        "number": { "type": "integer" }
                    },
                    "required": ["owner", "number"]
                })),
            ),
        ];
        let content = render_skillsync("GitHub", &tools);
        assert!(content.contains("fn get_pull_request("), "should use bare name");
        assert!(content.contains("owner: String"), "string → String");
        assert!(content.contains("number: Int"), "integer → Int");
        assert!(content.contains("/// Get a pull request"), "description as doc comment");
    }

    #[test]
    fn optional_params_have_question_mark() {
        let tools = vec![tool(
            "GitHub.list_prs",
            None,
            Some(json!({
                "type": "object",
                "properties": {
                    "owner": { "type": "string" },
                    "state": { "type": "string" }
                },
                "required": ["owner"]
            })),
        )];
        let content = render_skillsync("GitHub", &tools);
        assert!(content.contains("owner: String"), "required has no ?");
        assert!(content.contains("state: String?"), "optional has ?");
    }

    #[test]
    fn boolean_maps_to_bool_type() {
        let tools = vec![tool(
            "FileSystem.write_file",
            None,
            Some(json!({
                "type": "object",
                "properties": { "create_dirs": { "type": "boolean" } },
                "required": []
            })),
        )];
        let content = render_skillsync("FileSystem", &tools);
        assert!(content.contains("create_dirs: Bool?"), "boolean → Bool");
    }

    #[test]
    fn parse_tools_list_meta_parses_correctly() {
        let response = r#"{"jsonrpc":"2.0","id":2,"result":{"tools":[
            {"name":"get_pr","description":"Get PR","inputSchema":{"type":"object","properties":{"number":{"type":"integer"}},"required":["number"]}}
        ]}}"#;
        let tools = crate::verifier::parse_tools_list_meta(response, "GitHub").unwrap();
        assert_eq!(tools.len(), 1);
        assert_eq!(tools[0].name, "GitHub.get_pr");
        assert_eq!(tools[0].description.as_deref(), Some("Get PR"));
        assert!(tools[0].input_schema.is_some());
    }
}
