/// `brief skillgen` — generates a `.briefskill` typed interface from a skill directory.
///
/// Reads `<skill-dir>/README.md` and emits `<skill-dir>/<SkillName>.briefskill`.
/// Supports two extraction paths:
///   - Offline: structured markdown parsing (looks for "## Interface", "## Functions", etc.)
///   - Online:  LLM-enhanced (set BRIEF_LLM_API_KEY to enable)
///
/// Staleness detection: SHA-256 of README.md is embedded in the header.
/// `brief skillgen --check` compares current README hash against the stored hash.

use std::path::Path;
use colored::Colorize;
use sha2::{Sha256, Digest};

// ─────────────────────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────────────────────

/// Generate (or regenerate) a `.briefskill` interface from a skill directory.
pub fn skillgen(skill_path: &Path) -> bool {
    let skill_name = skill_name(skill_path);
    let readme_path = match require_readme(skill_path) {
        Some(p) => p,
        None    => return false,
    };
    let readme = match read_readme(&readme_path) {
        Some(s) => s,
        None    => return false,
    };

    println!("{} Generating interface for skill '{}'...", "●".blue().bold(), skill_name.bold());
    println!("  {} reading {}", "→".dimmed(), readme_path.display());

    let sha = sha256_hex(readme.as_bytes());

    // Try offline extraction first; fall back to LLM if empty and key is set.
    let functions = extract_offline(&readme, &skill_name);
    let (functions, used_llm) = if functions.is_empty() {
        match try_llm_extraction(&readme, &skill_name) {
            Some(fns) => (fns, true),
            None      => (functions, false),
        }
    } else {
        (functions, false)
    };

    let content = render_briefskill(&skill_name, &functions, &sha, &readme_path, used_llm);
    let output_path = skill_path.join(format!("{skill_name}.briefskill"));

    match std::fs::write(&output_path, &content) {
        Ok(_) => {
            println!("  {} {}", "✅".green(), output_path.display().to_string().green());
            if used_llm {
                println!("  {} interface extracted via LLM", "✦".cyan().bold());
            }
            println!();
            println!("{}", "Generated interface:".bold());
            println!("{}", content.dimmed());
        }
        Err(e) => {
            eprintln!("{}: cannot write {}: {}", "error".red().bold(), output_path.display(), e);
            return false;
        }
    }

    if functions.is_empty() {
        println!();
        println!("{} No typed functions extracted — the interface is empty.", "⚠".yellow().bold());
        println!("  {} Add an `## Interface` section to README.md with function signatures.", "hint:".cyan().bold());
        println!("  {} Set BRIEF_LLM_API_KEY to enable AI-assisted extraction.", "hint:".cyan().bold());
    }

    true
}

/// Check whether the existing `.briefskill` is up-to-date with the README.
/// Returns `true` if fresh, `false` if stale or missing. CI-friendly.
pub fn skillgen_check(skill_path: &Path) -> bool {
    let skill_name = skill_name(skill_path);
    let readme_path = match require_readme(skill_path) {
        Some(p) => p,
        None    => return false,
    };
    let readme = match read_readme(&readme_path) {
        Some(s) => s,
        None    => return false,
    };
    let current_sha = sha256_hex(readme.as_bytes());

    let skill_file = skill_path.join(format!("{skill_name}.briefskill"));

    if !skill_file.exists() {
        eprintln!(
            "{}: {}.briefskill not found",
            "stale".red().bold(), skill_name
        );
        eprintln!("  {} run: brief skillgen {}", "fix:".cyan().bold(), skill_path.display());
        return false;
    }

    let existing = match std::fs::read_to_string(&skill_file) {
        Ok(s)  => s,
        Err(e) => {
            eprintln!("{}: cannot read {}: {}", "error".red().bold(), skill_file.display(), e);
            return false;
        }
    };

    let stored_sha = extract_stored_sha(&existing);

    match stored_sha {
        Some(sha) if sha == current_sha => {
            println!("{} {} is up-to-date (sha256: {}…)", "✅".green(), skill_file.display(), &sha[..12]);
            true
        }
        Some(sha) => {
            eprintln!("{}: {}.briefskill is stale", "stale".red().bold(), skill_name);
            eprintln!("  stored sha256: {}…", &sha[..12]);
            eprintln!("  current sha256: {}…", &current_sha[..12]);
            eprintln!("  {} run: brief skillgen {}", "fix:".cyan().bold(), skill_path.display());
            false
        }
        None => {
            // Legacy file without a sha256 header — treat as stale.
            eprintln!("{}: {}.briefskill has no sha256 header (generated by old brief skillgen)", "stale".red().bold(), skill_name);
            eprintln!("  {} run: brief skillgen {}", "fix:".cyan().bold(), skill_path.display());
            false
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// .briefskill parsing (for cross-file type checking)
// ─────────────────────────────────────────────────────────────────────────────

/// A parsed skill interface: name + list of typed functions.
#[derive(Debug, Clone)]
pub struct SkillInterface {
    #[allow(dead_code)]
    pub name: String,
    pub effects: Vec<String>,
    pub funcs: Vec<SkillFn>,
}

/// A static constraint on a skill function parameter.
/// These are enforced by `brief check` without any network calls.
#[derive(Debug, Clone, PartialEq)]
pub enum StaticConstraint {
    /// `@range(min, max)` — integer must be in [min, max].
    Range(i64, i64),
    /// `@enum("v1", "v2", ...)` — must be one of the listed values.
    Enum(Vec<String>),
    /// `@matches("regex")` — string must match the regex pattern.
    Matches(String),
    /// `@nonEmpty` — string/collection must not be empty.
    NonEmpty,
}

/// A single parsed parameter from a `.briefskill` function signature.
#[derive(Debug, Clone)]
pub struct SkillParam {
    pub name:               String,
    /// The base type name (e.g. "Int", "String", "UserProfile").
    pub base_type:          String,
    /// Static constraints extracted from `@range`, `@enum`, `@matches`, `@nonEmpty` annotations.
    pub static_constraints: Vec<StaticConstraint>,
    /// Any other `@xyz` annotations — require a verifier configured in `brief.toml`.
    pub dynamic_attrs:      Vec<String>,
}

/// A single function entry from a `.briefskill` file.
#[derive(Debug, Clone)]
pub struct SkillFn {
    pub name:        String,
    /// Kept for backward compatibility with the type-checker.
    pub arg_count:   usize,
    /// Full parameter information with constraint annotations.
    pub params:      Vec<SkillParam>,
    pub return_type: String,
    /// Optional human-readable description from `///` doc comments in the .briefskill file.
    /// Populated by `brief skillsync` from the MCP server's `tools/list` description field.
    pub description: Option<String>,
}

/// Parse a `.briefskill` file into a `SkillInterface`.
/// Returns `None` if the file cannot be parsed at all.
pub fn parse_briefskill(content: &str) -> Option<SkillInterface> {
    let mut name: Option<String> = None;
    let mut effects = Vec::new();
    let mut funcs = Vec::new();
    let mut in_interface = false;
    let mut pending_doc: Option<String> = None;

    for line in content.lines() {
        let t = line.trim();

        // `///` doc comment — accumulate for the next function.
        if let Some(doc) = t.strip_prefix("///") {
            let doc_text = doc.trim().to_string();
            pending_doc = Some(match pending_doc.take() {
                Some(prev) if prev.is_empty() => doc_text,
                Some(prev) => format!("{prev} {doc_text}"),
                None => doc_text,
            });
            continue;
        }

        // Other comments — don't clear pending doc, just skip.
        if t.starts_with("//") {
            continue;
        }

        // Non-comment, non-fn line — clear pending doc if not inside interface.
        if !in_interface {
            if let Some(parsed_effects) = parse_effects_decl(t) {
                effects = parsed_effects;
                pending_doc = None;
                continue;
            }
        }

        // `interface SkillName {`
        if t.starts_with("interface ") && t.ends_with('{') {
            let n = t["interface ".len()..t.len() - 1].trim().to_string();
            name = Some(n);
            in_interface = true;
            pending_doc = None;
            continue;
        }

        if t == "}" && in_interface {
            in_interface = false;
            pending_doc = None;
            continue;
        }

        if in_interface {
            if let Some(sig) = parse_fn_sig(t) {
                let params: Vec<SkillParam> = sig
                    .params
                    .iter()
                    .map(|(pname, ptype)| parse_skill_param(pname, ptype))
                    .collect();
                funcs.push(SkillFn {
                    name: sig.name,
                    arg_count: params.len(),
                    params,
                    return_type: sig.return_type,
                    description: pending_doc.take(),
                });
            } else {
                // Non-fn line inside interface — clear pending doc.
                pending_doc = None;
            }
        }
    }

    name.map(|n| SkillInterface {
        name: n,
        effects,
        funcs,
    })
}

fn parse_effects_decl(line: &str) -> Option<Vec<String>> {
    let rest = line.strip_prefix("effects")?.trim();
    let inner = rest.strip_prefix('[')?.strip_suffix(']')?;
    Some(
        inner
            .split(',')
            .map(str::trim)
            .filter(|effect| !effect.is_empty())
            .map(ToString::to_string)
            .collect(),
    )
}

// ─────────────────────────────────────────────────────────────────────────────
// Parameter constraint parsing
// ─────────────────────────────────────────────────────────────────────────────

/// Parse a `.briefskill` parameter like `"input"` + `"@range(0, 100) Int"`
/// into a `SkillParam` with static constraints and dynamic attrs separated.
fn parse_skill_param(name: &str, type_str: &str) -> SkillParam {
    let mut static_constraints = Vec::new();
    let mut dynamic_attrs = Vec::new();
    let mut rest = type_str.trim();

    // Peel off leading annotations one at a time until the base type is reached.
    while rest.starts_with('@') {
        let ann;
        if let Some(paren_pos) = rest.find('(') {
            // Check that the paren is part of THIS annotation (before any space).
            let space_before_paren = rest[1..paren_pos].contains(' ');
            if !space_before_paren {
                // Annotation with args: scan for matching closing paren.
                let mut depth = 0usize;
                let mut end = None;
                for (i, ch) in rest.char_indices() {
                    match ch {
                        '(' => { depth += 1; }
                        ')' => {
                            depth -= 1;
                            if depth == 0 { end = Some(i + 1); break; }
                        }
                        _ => {}
                    }
                }
                match end {
                    Some(e) => {
                        ann = &rest[..e];
                        rest = rest[e..].trim_start();
                    }
                    None => {
                        // Unclosed paren — malformed annotation; treat remainder as base type.
                        break;
                    }
                }
            } else {
                // Space before paren → this annotation has no args; paren belongs to next token.
                let sp = rest.find(' ').unwrap_or(rest.len());
                ann = &rest[..sp];
                rest = rest[sp..].trim_start();
            }
        } else {
            // No paren: annotation ends at next space or end of string.
            let sp = rest.find(' ').unwrap_or(rest.len());
            ann = &rest[..sp];
            rest = rest[sp..].trim_start();
        }

        let name_end = ann.find('(').unwrap_or(ann.len());
        let ann_name = &ann[..name_end];

        match ann_name {
            "@range" => {
                if let Some(r) = parse_range_args(&ann[name_end..]) {
                    static_constraints.push(StaticConstraint::Range(r.0, r.1));
                }
            }
            "@enum" => {
                let vals = parse_enum_args(&ann[name_end..]);
                if !vals.is_empty() {
                    static_constraints.push(StaticConstraint::Enum(vals));
                }
            }
            "@matches" => {
                if let Some(pat) = parse_string_arg(&ann[name_end..]) {
                    static_constraints.push(StaticConstraint::Matches(pat));
                }
            }
            "@nonEmpty" => {
                static_constraints.push(StaticConstraint::NonEmpty);
            }
            _ => {
                dynamic_attrs.push(ann.to_string());
            }
        }
    }

    SkillParam {
        name: name.to_string(),
        base_type: rest.to_string(),
        static_constraints,
        dynamic_attrs,
    }
}

fn parse_range_args(args: &str) -> Option<(i64, i64)> {
    let inner = args.strip_prefix('(')?.strip_suffix(')')?;
    let mut parts = inner.splitn(2, ',');
    let min = parts.next()?.trim().parse::<i64>().ok()?;
    let max = parts.next()?.trim().parse::<i64>().ok()?;
    Some((min, max))
}

fn parse_enum_args(args: &str) -> Vec<String> {
    let inner = match args.strip_prefix('(').and_then(|s| s.strip_suffix(')')) {
        Some(s) => s,
        None    => return vec![],
    };
    inner.split(',')
        .filter_map(|s| {
            let s = s.trim().trim_matches('"').trim_matches('\'');
            if s.is_empty() { None } else { Some(s.to_string()) }
        })
        .collect()
}

fn parse_string_arg(args: &str) -> Option<String> {
    let inner = args.strip_prefix('(')?.strip_suffix(')')?;
    Some(inner.trim().trim_matches('"').trim_matches('\'').to_string())
}

/// Extract the sha256 value embedded in a `.briefskill` header comment.
/// Looks for `// Source: ... (sha256: <hex>)`.
pub fn extract_stored_sha(content: &str) -> Option<String> {
    for line in content.lines() {
        if let Some(pos) = line.find("(sha256: ") {
            let rest = &line[pos + "(sha256: ".len()..];
            let sha = rest.trim_end_matches(')').trim().to_string();
            if sha.len() == 64 { return Some(sha); }
        }
    }
    None
}

// ─────────────────────────────────────────────────────────────────────────────
// Offline markdown extraction
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug)]
struct FnSig {
    name:        String,
    params:      Vec<(String, String)>,
    return_type: String,
    #[allow(dead_code)]
    doc:         Option<String>,
}

fn extract_offline(markdown: &str, _skill_name: &str) -> Vec<FnSig> {
    let mut fns = Vec::new();
    let mut in_interface = false;

    for line in markdown.lines() {
        let trimmed = line.trim();

        if trimmed.starts_with("## Interface")
            || trimmed.starts_with("## Functions")
            || trimmed.starts_with("## API")
            || trimmed.starts_with("## Capabilities")
        {
            in_interface = true;
            continue;
        }

        if trimmed.starts_with("## ") && in_interface {
            in_interface = false;
        }

        if !in_interface { continue; }

        let sig_line = if trimmed.starts_with("- `fn ") || trimmed.starts_with("* `fn ") {
            trimmed.trim_start_matches("- ").trim_start_matches("* ").trim_matches('`')
        } else if trimmed.starts_with("fn ") {
            trimmed
        } else {
            continue;
        };

        if let Some(sig) = parse_fn_sig(sig_line) {
            fns.push(sig);
        }
    }

    fns
}

fn parse_fn_sig(sig: &str) -> Option<FnSig> {
    let rest = sig.strip_prefix("fn ")?;
    // Strip generic type params like `<T>` after fn name. Use an owned String
    // to avoid .leak() — the local variable lives for the function's duration.
    let owned: String;
    let rest: &str = if let Some(lt) = rest.find('<') {
        if let Some(gt) = rest.find(">(") {
            let name_part = &rest[..lt];
            let after_generics = &rest[gt + 1..];
            owned = format!("{name_part}{after_generics}");
            &owned
        } else { rest }
    } else { rest };

    // Find the opening `(` that starts the param list.
    let open = rest.find('(')?;
    let name = rest[..open].trim().to_string();

    // Find the matching closing `)` using paren depth.
    // This handles nested parens in annotations like @enum("a","b") and @range(0,100).
    let after_open = &rest[open + 1..];
    let mut depth = 1usize;
    let mut close = None;
    for (i, ch) in after_open.char_indices() {
        match ch {
            '(' => depth += 1,
            ')' => {
                depth -= 1;
                if depth == 0 { close = Some(i); break; }
            }
            _ => {}
        }
    }
    let close = close?;
    let params_str = &after_open[..close];
    let after_close = &after_open[close + 1..];

    let return_type = after_close.trim()
        .strip_prefix("->").unwrap_or("Unit")
        .trim()
        .to_string();

    // Split params by `,` at depth-0 only (respects nested annotation parens).
    let params = split_params(params_str);

    Some(FnSig { name, params, return_type, doc: None })
}

/// Split a parameter list string by top-level commas (paren-depth aware).
/// `"x: @range(0, 100) Int, y: String"` → `[("x","@range(0, 100) Int"), ("y","String")]`
fn split_params(params_str: &str) -> Vec<(String, String)> {
    let mut result = Vec::new();
    let mut depth = 0usize;
    let mut seg_start = 0usize;

    for (i, ch) in params_str.char_indices() {
        match ch {
            '(' | '[' | '{' => depth += 1,
            ')' | ']' | '}' => { if depth > 0 { depth -= 1; } }
            ',' if depth == 0 => {
                push_param(&mut result, params_str[seg_start..i].trim());
                seg_start = i + 1;
            }
            _ => {}
        }
    }
    // last segment
    let last = params_str[seg_start..].trim();
    if !last.is_empty() {
        push_param(&mut result, last);
    }
    result
}

fn push_param(out: &mut Vec<(String, String)>, param: &str) {
    if param.is_empty() { return; }
    // Split on first `:` that isn't inside angle brackets (e.g. `Result<T, E>`)
    // Simple approach: split at first `:` (colons inside `<>` are less common in param names).
    if let Some(colon) = param.find(':') {
        let pname = param[..colon].trim().to_string();
        let ptype = param[colon + 1..].trim().to_string();
        out.push((pname, ptype));
    } else {
        out.push((param.to_string(), "Any".to_string()));
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// LLM extraction (online path)
// ─────────────────────────────────────────────────────────────────────────────

/// Maximum README size sent to the LLM (64 KB).
const MAX_README_LLM_BYTES: usize = 64 * 1024;
/// Maximum LLM response body size read (64 KB).
const MAX_LLM_RESPONSE_BYTES: usize = 64 * 1024;

/// If `BRIEF_LLM_API_KEY` is set, call the LLM to extract typed function signatures.
/// Returns `None` if no key is configured or the call fails.
fn try_llm_extraction(readme: &str, skill_name: &str) -> Option<Vec<FnSig>> {
    let api_key = std::env::var("BRIEF_LLM_API_KEY").ok()?;
    // Auto-detect provider from URL or BRIEF_LLM_PROVIDER env var.
    let provider = std::env::var("BRIEF_LLM_PROVIDER").unwrap_or_else(|_| "anthropic".into());
    let api_url = std::env::var("BRIEF_LLM_URL")
        .unwrap_or_else(|_| match provider.as_str() {
            "openai" => "https://api.openai.com/v1/chat/completions".into(),
            _        => "https://api.anthropic.com/v1/messages".into(),
        });

    // Cap README size before embedding in the prompt.
    let readme_capped = if readme.len() > MAX_README_LLM_BYTES {
        eprintln!(
            "  {} README is large ({} bytes); truncating to {} bytes for LLM extraction",
            "⚠".yellow().bold(), readme.len(), MAX_README_LLM_BYTES
        );
        &readme[..MAX_README_LLM_BYTES]
    } else {
        readme
    };

    let prompt = format!(
        "You are a type extractor for the Brief programming language.\n\
         Given this skill README, extract all callable functions as Brief interface declarations.\n\n\
         Brief param annotations (include when the README documents constraints):\n\
         - @range(min, max) for numeric ranges: `amount: @range(1, 1000000) Int`\n\
         - @enum(\"v1\",\"v2\") for allowed string values: `status: @enum(\"active\",\"inactive\") String`\n\
         - @matches(\"regex\") for format constraints: `email: @matches(\"[^@]+@[^@]+\") String`\n\
         - @nonEmpty for required non-empty strings: `query: @nonEmpty String`\n\
         - @custom-annotation for domain-specific verification: `webhook: @stripe-hook String`\n\n\
         Output ONLY a JSON array, no markdown, no explanation:\n\
         [{{\"name\":\"query\",\"params\":[\"op: Operation\",\"limit: @range(1,100) Int\"],\"return\":\"Result<T, QueryError>\"}}]\n\n\
         Skill name: {skill_name}\n\n\
         README:\n{readme_capped}"
    );

    println!("  {} calling {} for interface extraction...", "✦".cyan().bold(), provider);

    let (body, req) = if provider == "openai" {
        let model = std::env::var("BRIEF_LLM_MODEL")
            .unwrap_or_else(|_| "gpt-4o-mini".into());
        let b = serde_json::json!({
            "model": model,
            "max_tokens": 1024,
            "messages": [{"role": "user", "content": prompt}]
        });
        let r = ureq::post(&api_url)
            .set("Authorization", &format!("Bearer {api_key}"))
            .set("Content-Type", "application/json");
        (b, r)
    } else {
        let model = std::env::var("BRIEF_LLM_MODEL")
            .unwrap_or_else(|_| "claude-3-5-haiku-20241022".into());
        let b = serde_json::json!({
            "model": model,
            "max_tokens": 1024,
            "messages": [{"role": "user", "content": prompt}]
        });
        let r = ureq::post(&api_url)
            .set("x-api-key", &api_key)
            .set("anthropic-version", "2023-06-01")
            .set("content-type", "application/json");
        (b, r)
    };

    let response = req.send_json(&body);

    match response {
        Ok(resp) => {
            use std::io::Read;
            let mut body_str = String::new();
            if resp.into_reader().take(MAX_LLM_RESPONSE_BYTES as u64)
                .read_to_string(&mut body_str).is_err()
            {
                return None;
            }
            let json: serde_json::Value = serde_json::from_str(&body_str).ok()?;
            // Anthropic: json["content"][0]["text"], OpenAI: json["choices"][0]["message"]["content"]
            let text = json["content"][0]["text"].as_str()
                .or_else(|| json["choices"][0]["message"]["content"].as_str())?;
            parse_llm_json(text)
        }
        Err(e) => {
            eprintln!("  {} LLM call failed: {}", "⚠".yellow().bold(), e);
            eprintln!("  {} falling back to offline extraction", "→".dimmed());
            None
        }
    }
}

/// Parse the JSON array returned by the LLM into FnSig structs.
/// Handles annotated type strings like `"@range(1,100) Int"` — annotations
/// are preserved in the type string so they flow through `parse_fn_sig`.
fn parse_llm_json(text: &str) -> Option<Vec<FnSig>> {
    // Strip markdown code fences if present.
    let text = text.trim();
    let text = text.strip_prefix("```json").unwrap_or(text);
    let text = text.strip_prefix("```").unwrap_or(text);
    let text = text.strip_suffix("```").unwrap_or(text).trim();

    let arr: serde_json::Value = serde_json::from_str(text).ok()?;
    let arr = arr.as_array()?;

    let mut fns = Vec::new();
    for item in arr {
        let name = item["name"].as_str()?.to_string();
        let return_type = item["return"].as_str().unwrap_or("Unit").to_string();
        let params = item["params"].as_array()
            .map(|ps| ps.iter().filter_map(|p| {
                let s = p.as_str()?;
                if let Some((n, t)) = s.split_once(':') {
                    Some((n.trim().to_string(), t.trim().to_string()))
                } else {
                    Some((s.to_string(), "Any".to_string()))
                }
            }).collect::<Vec<_>>())
            .unwrap_or_default();

        fns.push(FnSig { name, params, return_type, doc: None });
    }

    if fns.is_empty() { None } else { Some(fns) }
}

// ─────────────────────────────────────────────────────────────────────────────
// .briefskill rendering
// ─────────────────────────────────────────────────────────────────────────────

fn render_briefskill(skill_name: &str, fns: &[FnSig], sha: &str, source_path: &Path, used_llm: bool) -> String {
    let extractor = if used_llm { "brief skillgen (LLM)" } else { "brief skillgen (offline)" };
    let mut out = String::new();

    out.push_str(&format!(
        "// Auto-generated by `{extractor} v0.1.0`\n\
         // Source: {source} (sha256: {sha})\n\
         // Regenerate: brief skillgen {dir}\n\
         // Do not edit manually.\n\n",
        source = source_path.display(),
        dir    = source_path.parent().map(|p| p.display().to_string()).unwrap_or_default(),
    ));

    out.push_str(&format!("interface {skill_name} {{\n"));

    if fns.is_empty() {
        out.push_str("    // No typed functions extracted.\n");
        out.push_str("    // Add an `## Interface` section to README.md with function signatures,\n");
        out.push_str("    // or set BRIEF_LLM_API_KEY for AI-assisted extraction.\n");
    } else {
        for f in fns {
            if let Some(doc) = &f.doc {
                if !doc.is_empty() {
                    out.push_str(&format!("    /// {doc}\n"));
                }
            }
            let params = f.params.iter()
                .map(|(n, t)| format!("{n}: {t}"))
                .collect::<Vec<_>>()
                .join(", ");
            out.push_str(&format!("    fn {}({}) -> {}\n", f.name, params, f.return_type));
        }
    }

    out.push_str("}\n");
    out
}

// ─────────────────────────────────────────────────────────────────────────────
// Helpers
// ─────────────────────────────────────────────────────────────────────────────

fn skill_name(skill_path: &Path) -> String {
    skill_path.file_name().and_then(|n| n.to_str()).unwrap_or("UnknownSkill").to_string()
}

fn require_readme(skill_path: &Path) -> Option<std::path::PathBuf> {
    let path = skill_path.join("README.md");
    if !path.exists() {
        eprintln!("{}: no README.md found in {}", "error".red().bold(), skill_path.display());
        eprintln!("  {} Create a README.md describing the skill's capabilities.", "hint:".cyan().bold());
        return None;
    }
    Some(path)
}

fn read_readme(path: &Path) -> Option<String> {
    match std::fs::read_to_string(path) {
        Ok(s)  => Some(s),
        Err(e) => {
            eprintln!("{}: cannot read {}: {}", "error".red().bold(), path.display(), e);
            None
        }
    }
}

fn sha256_hex(data: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(data);
    hex::encode(hasher.finalize())
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_sha256_is_deterministic() {
        let h1 = sha256_hex(b"hello");
        let h2 = sha256_hex(b"hello");
        assert_eq!(h1, h2);
        assert_eq!(h1.len(), 64);
    }

    #[test]
    fn test_extract_stored_sha() {
        let content = "// Source: README.md (sha256: abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890)\n";
        let sha = extract_stored_sha(content);
        assert_eq!(sha, Some("abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890".to_string()));
    }

    #[test]
    fn test_extract_stored_sha_none_for_old_format() {
        let content = "// Source: README.md (crc32: deadbeef)\n";
        assert_eq!(extract_stored_sha(content), None);
    }

    #[test]
    fn test_parse_briefskill_basic() {
        let content = r#"
// Auto-generated
// Source: README.md (sha256: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)

interface GraphQL {
    fn query(op: Operation) -> Result<T, QueryError>
    fn mutate(op: Operation) -> Result<T, QueryError>
}
"#;
        let iface = parse_briefskill(content).expect("should parse");
        assert_eq!(iface.name, "GraphQL");
        assert!(iface.effects.is_empty());
        assert_eq!(iface.funcs.len(), 2);
        assert_eq!(iface.funcs[0].name, "query");
        assert_eq!(iface.funcs[0].arg_count, 1);
        assert_eq!(iface.funcs[1].name, "mutate");
    }

    #[test]
    fn test_parse_briefskill_empty_interface() {
        let content = "interface Stub {\n    // No functions\n}\n";
        let iface = parse_briefskill(content).expect("should parse");
        assert_eq!(iface.name, "Stub");
        assert_eq!(iface.funcs.len(), 0);
    }

    #[test]
    fn test_parse_briefskill_effects() {
        let content = r#"
        effects [network, cache-read]
        interface NetworkService {
            fn fetch(url: String) -> Response
        }
        "#;
        let iface = parse_briefskill(content).expect("should parse");
        assert_eq!(iface.effects, vec!["network", "cache-read"]);
    }

    #[test]
    fn test_offline_extraction() {
        let md = r#"
# MySkill

## Interface

- `fn doThing(input: String) -> Result<Unit, MyError>`
- `fn getStatus() -> Status`
"#;
        let fns = extract_offline(md, "MySkill");
        assert_eq!(fns.len(), 2);
        assert_eq!(fns[0].name, "doThing");
        assert_eq!(fns[0].params.len(), 1);
        assert_eq!(fns[1].name, "getStatus");
        assert_eq!(fns[1].params.len(), 0);
    }

    #[test]
    fn test_render_briefskill_includes_sha() {
        let sha = "a".repeat(64);
        let fns: Vec<FnSig> = vec![];
        let path = std::path::Path::new("README.md");
        let rendered = render_briefskill("TestSkill", &fns, &sha, path, false);
        assert!(rendered.contains(&format!("sha256: {sha}")));
        assert!(rendered.contains("interface TestSkill {"));
    }

    #[test]
    fn test_parse_briefskill_with_constraints() {
        let content = r#"
interface MapperService {
    fn mapValue(input: @range(0, 100) Int) -> Code
    fn classify(cat: @enum("ok", "warn", "err") String) -> Status
    fn createPayment(amount: @range(100, 1000000) Int, webhook: @stripe-hook String) -> Result
    fn query(op: UserProfile) -> Result<T, QueryError>
}
"#;
        let iface = parse_briefskill(content).expect("should parse");
        assert_eq!(iface.name, "MapperService");
        assert_eq!(iface.funcs.len(), 4);

        // mapValue: @range(0, 100) Int
        let f0 = &iface.funcs[0];
        assert_eq!(f0.name, "mapValue");
        assert_eq!(f0.arg_count, 1);
        let p0 = &f0.params[0];
        assert_eq!(p0.base_type, "Int");
        assert_eq!(p0.static_constraints, vec![StaticConstraint::Range(0, 100)]);
        assert!(p0.dynamic_attrs.is_empty());

        // classify: @enum("ok", "warn", "err") String
        let f1 = &iface.funcs[1];
        let p1 = &f1.params[0];
        assert_eq!(p1.base_type, "String");
        assert_eq!(p1.static_constraints, vec![StaticConstraint::Enum(vec![
            "ok".into(), "warn".into(), "err".into(),
        ])]);

        // createPayment: @range on first param, @stripe-hook dynamic on second
        let f2 = &iface.funcs[2];
        assert_eq!(f2.arg_count, 2);
        let p2a = &f2.params[0];
        assert_eq!(p2a.base_type, "Int");
        assert_eq!(p2a.static_constraints, vec![StaticConstraint::Range(100, 1000000)]);
        let p2b = &f2.params[1];
        assert_eq!(p2b.base_type, "String");
        assert!(p2b.static_constraints.is_empty());
        assert_eq!(p2b.dynamic_attrs, vec!["@stripe-hook"]);

        // query: no constraints, plain type
        let f3 = &iface.funcs[3];
        let p3 = &f3.params[0];
        assert_eq!(p3.base_type, "UserProfile");
        assert!(p3.static_constraints.is_empty());
        assert!(p3.dynamic_attrs.is_empty());
    }

    #[test]
    fn test_parse_skill_param_range() {
        let p = parse_skill_param("input", "@range(0, 100) Int");
        assert_eq!(p.base_type, "Int");
        assert_eq!(p.static_constraints, vec![StaticConstraint::Range(0, 100)]);
        assert!(p.dynamic_attrs.is_empty());
    }

    #[test]
    fn test_parse_skill_param_enum() {
        let p = parse_skill_param("level", "@enum(\"low\", \"med\", \"high\") String");
        assert_eq!(p.base_type, "String");
        assert_eq!(p.static_constraints,
            vec![StaticConstraint::Enum(vec!["low".into(), "med".into(), "high".into()])]);
    }

    #[test]
    fn test_parse_skill_param_matches() {
        let p = parse_skill_param("email", "@matches(\"[^@]+@[^@]+\") String");
        assert_eq!(p.base_type, "String");
        assert_eq!(p.static_constraints, vec![StaticConstraint::Matches("[^@]+@[^@]+".into())]);
    }

    #[test]
    fn test_parse_skill_param_dynamic() {
        let p = parse_skill_param("hook", "@stripe-hook String");
        assert_eq!(p.base_type, "String");
        assert!(p.static_constraints.is_empty());
        assert_eq!(p.dynamic_attrs, vec!["@stripe-hook"]);
    }

    #[test]
    fn test_parse_skill_param_no_annotation() {
        let p = parse_skill_param("user", "UserProfile");
        assert_eq!(p.base_type, "UserProfile");
        assert!(p.static_constraints.is_empty());
        assert!(p.dynamic_attrs.is_empty());
    }

    #[test]
    fn test_parse_briefskill_doc_comments_captured() {
        let content = r#"
interface GitHub {
    /// Get a pull request by number
    fn get_pull_request(owner: String, repo: String, number: Int) -> String
    /// Create a review comment on a pull request
    fn create_review_comment(owner: String, repo: String, number: Int, body: String) -> String
    fn list_commits(owner: String, repo: String) -> String
}
"#;
        let iface = parse_briefskill(content).expect("should parse");
        assert_eq!(iface.funcs.len(), 3);
        assert_eq!(
            iface.funcs[0].description.as_deref(),
            Some("Get a pull request by number")
        );
        assert_eq!(
            iface.funcs[1].description.as_deref(),
            Some("Create a review comment on a pull request")
        );
        // No doc comment → None
        assert!(iface.funcs[2].description.is_none());
    }

    #[test]
    fn test_parse_briefskill_regular_comment_not_captured() {
        let content = r#"
interface GitHub {
    // internal: legacy endpoint
    fn get_pull_request(owner: String) -> String
}
"#;
        let iface = parse_briefskill(content).expect("should parse");
        // Regular `//` comment should NOT become a description (only `///` does)
        assert!(iface.funcs[0].description.is_none());
    }

    #[test]
    fn test_render_briefskill_emits_doc_comments() {
        let fns = vec![
            FnSig {
                name: "getUser".into(),
                params: vec![("id".into(), "String".into())],
                return_type: "User".into(),
                doc: Some("Fetch a user by ID".into()),
            },
            FnSig {
                name: "deleteUser".into(),
                params: vec![("id".into(), "String".into())],
                return_type: "Unit".into(),
                doc: None,
            },
        ];
        let rendered = render_briefskill("UserService", &fns, &"a".repeat(64), std::path::Path::new("README.md"), false);
        assert!(rendered.contains("    /// Fetch a user by ID\n"), "doc comment must be rendered");
        assert!(rendered.contains("    fn getUser(id: String) -> User"), "fn must follow doc comment");
        assert!(!rendered.contains("/// deleteUser"), "no doc for deleteUser");
    }
}
